# This file is used to filter the output of the tools
# Add regex for each tool to exclude output from being sent to llm
ffuf:
  - ".*:: Progress:.*"
curl:
  - >
    .*(?:\d{1,2}|\-{2}):(?:\d{2}|\-{2}):(?:\d{2}|\-{2})\s+
    (?:\d{1,2}|\-{2}):(?:\d{2}|\-{2}):(?:\d{2}|\-{2})\s+
    (?:\d{1,2}|\-{2}):(?:\d{2}|\-{2}):(?:\d{2}|\-{2}).*
gobuster:
  - "^Progress: \\d+ / \\d+ \\\([0-9]+\\.[0-9]+%\\\)$"
