apt:
  - openvpn
  - nmap
  - feroxbuster
  - nikto
  - whatweb
  - dnsutils
  - smtp-user-enum
  - lftp
  - ftp
  - hydra
  - onesixtyone
  - snmp
  - snmpd
  - snmpcheck
  - smbclient
  - enum4linux
  - rpcbind
  - nbtscan
  - seclists
  - curl
  - git
  - unzip
  - iproute2
  - net-tools
  - traceroute
  - exploitdb
  - python3
  - python3-pip
  - golang
  - netcat-traditional
  - wpscan
  - whatweb

pip:
  - httpie
  - git-dumper

custom:
  swaks: curl -o /usr/local/bin/swaks https://jetmore.org/john/code/swaks/files/swaks && chmod +x /usr/local/bin/swaks
  smbmap: git clone https://github.com/ShawnDEvans/smbmap.git /opt/smbmap && ln -s /opt/smbmap/smbmap.py /usr/local/bin/smbmap